#ifndef SPECTACULAR_AI_CAMERA_AVAILABILITY_HPP
#define SPECTACULAR_AI_CAMERA_AVAILABILITY_HPP

// This is auto-generated!
#define SPECTACULARAI_CAMERA_K4A
#define SPECTACULARAI_CAMERA_REALSENSE

#endif /* SPECTACULAR_AI_CAMERA_AVAILABILITY_HPP */
